package com.example.gpiApp.service;

import com.example.gpiApp.dto.ai.PrioritizationResultDTO;
import com.example.gpiApp.dto.ai.ProjectInsightDTO;
import com.example.gpiApp.dto.ai.RiskAssessmentDTO;
import com.example.gpiApp.dto.ai.TaskPrioritySuggestionDTO;
import com.example.gpiApp.dto.ai.TaskRiskDTO;
import com.example.gpiApp.entity.Project;
import com.example.gpiApp.entity.Task;
import com.example.gpiApp.exception.ResourceNotFoundException;
import com.example.gpiApp.repository.ProjectRepository;
import com.example.gpiApp.repository.TaskRepository;
import com.fasterxml.jackson.databind.JsonNode;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Intelligent assistant for project insights and task prioritisation.
 * <p>
 * <b>Mock-first design.</b> The narrative summaries and priority suggestions are
 * currently generated by a deterministic, rule-based engine that runs over the
 * project's real tasks (deadlines, progress, status, priority). This lets the full
 * feature - API, security, UI - ship and be demonstrated without an external model
 * or API key.
 * <p>
 * <b>Extension point.</b> To back this with a live model, replace the bodies of
 * {@link #buildSummary} and {@link #buildSuggestions} with a call to the Claude API,
 * passing the same {@code Project}/{@code Task} data as context. The DTO contracts and
 * the frontend remain unchanged; only the {@code source} field flips from MOCK to AI.
 */
@Service
@RequiredArgsConstructor
public class AiAssistantService {

    private static final String SOURCE_MOCK = "MOCK";
    private static final String SOURCE_AI = "AI";

    private static final String SUMMARY_SYSTEM_PROMPT = """
            You are a project-management assistant embedded in a task-management application.
            You are given a project's real metrics and its task list as JSON. Write a concise,
            professional assessment for the project manager.
            Respond with a SINGLE JSON object and nothing else, matching exactly:
            {"summary": "<2-4 sentence natural-language assessment>",
             "recommendations": ["<short actionable recommendation>", "..."]}
            Rules: base everything strictly on the data provided; do not invent tasks or numbers;
            keep the summary under 80 words; provide 1 to 4 recommendations ordered by impact;
            do not use emoji (accented characters for the response language are fine).""";

    private static final String PRIORITIES_SYSTEM_PROMPT = """
            You are a project-management assistant embedded in a task-management application.
            You are given a project's open tasks as JSON, each with a computed urgency score and a
            suggested priority. Write guidance for the project manager.
            Respond with a SINGLE JSON object and nothing else, matching exactly:
            {"overallAdvice": "<one sentence of overall guidance>",
             "reasons": [{"taskId": <number>, "reason": "<short justification for this task's urgency>"}]}
            Rules: base everything strictly on the data provided; do not invent tasks; provide one
            reason per task given; keep each reason under 25 words; do not use emoji.""";

    private static final String RISK_SYSTEM_PROMPT = """
            You are a project-management assistant embedded in a task-management application.
            You are given a project's predicted delivery risk and its at-risk tasks as JSON, where
            risk levels and predicted slip days were already computed. Write a concise risk briefing
            for the project manager.
            Respond with a SINGLE JSON object and nothing else, matching exactly:
            {"summary": "<2-4 sentence risk assessment naming the biggest threats>"}
            Rules: base everything strictly on the data provided; do not invent tasks or dates;
            keep the summary under 80 words; do not use emoji (accented characters for the response language are fine).""";

    private final ProjectRepository projectRepository;
    private final TaskRepository taskRepository;
    private final LangChainAiClient langChainClient;
    private final SystemSettingsService systemSettings;
    private final com.fasterxml.jackson.databind.ObjectMapper objectMapper = new com.fasterxml.jackson.databind.ObjectMapper();

    /** Append a language directive so AI narratives are written in the admin-configured language. */
    private String withLanguage(String systemPrompt) {
        String lang = systemSettings.getAiLanguageName();
        return systemPrompt + "\n\nLANGUAGE: Write every text field of your response (summary, headline, "
                + "recommendations, advice, reasons) entirely in " + lang
                + ", using that language's normal accented characters. Keep JSON keys and enum values unchanged.";
    }

    /** True when the LangChain.js + Gemini sidecar is configured; otherwise the rule-based engine is used. */
    private boolean anyAiEnabled() {
        return langChainClient.isEnabled();
    }

    // ── Public API ───────────────────────────────────────────────────────────

    @Transactional(readOnly = true)
    public ProjectInsightDTO generateProjectSummary(Long projectId) {
        Project project = projectRepository.findById(projectId)
                .orElseThrow(() -> new ResourceNotFoundException("Project not found with id: " + projectId));
        List<Task> tasks = taskRepository.findByProject(project);
        return buildSummary(project, tasks);
    }

    @Transactional(readOnly = true)
    public PrioritizationResultDTO suggestTaskPriorities(Long projectId) {
        Project project = projectRepository.findById(projectId)
                .orElseThrow(() -> new ResourceNotFoundException("Project not found with id: " + projectId));
        List<Task> tasks = taskRepository.findByProject(project);
        return buildSuggestions(project, tasks);
    }

    @Transactional(readOnly = true)
    public RiskAssessmentDTO assessProjectRisks(Long projectId) {
        Project project = projectRepository.findById(projectId)
                .orElseThrow(() -> new ResourceNotFoundException("Project not found with id: " + projectId));
        List<Task> tasks = taskRepository.findByProject(project);
        return buildRiskAssessment(project, tasks);
    }

    // ── Summary engine ─────────────────────────────────────────────────────────

    private ProjectInsightDTO buildSummary(Project project, List<Task> tasks) {
        long total = tasks.size();
        long completed = count(tasks, Task.TaskStatus.COMPLETED);
        long inProgress = count(tasks, Task.TaskStatus.IN_PROGRESS);
        long todo = count(tasks, Task.TaskStatus.TODO);
        long overdue = countOverdue(tasks);

        double completionRate = total > 0 ? round1((double) completed / total * 100) : 0;
        Integer daysRemaining = daysRemaining(project);

        String health = computeHealth(completionRate, overdue, total, project);
        String headline = healthHeadline(health, overdue);

        StringBuilder s = new StringBuilder();
        s.append("Project \"").append(project.getName()).append("\" currently holds ")
         .append(total).append(total == 1 ? " task" : " tasks")
         .append(", of which ").append(completed).append(" are completed (")
         .append(completionRate).append("% completion). ");

        if (inProgress > 0) {
            s.append(inProgress).append(inProgress == 1 ? " task is" : " tasks are")
             .append(" actively in progress");
            if (todo > 0) s.append(", and ").append(todo).append(" remain in the backlog");
            s.append(". ");
        } else if (todo > 0) {
            s.append(todo).append(todo == 1 ? " task is" : " tasks are")
             .append(" still in the backlog and not yet started. ");
        }

        if (overdue > 0) {
            s.append("Warning: ").append(overdue).append(overdue == 1 ? " task has" : " tasks have")
             .append(" passed their deadline and need immediate attention. ");
        } else {
            s.append("No tasks are currently overdue. ");
        }

        if (daysRemaining != null) {
            if (daysRemaining > 0) {
                s.append("There ").append(daysRemaining == 1 ? "is" : "are").append(" ")
                 .append(daysRemaining).append(daysRemaining == 1 ? " day" : " days")
                 .append(" remaining until the planned end date. ");
            } else {
                s.append("The planned end date has passed. ");
            }
        }

        s.append("\n\n").append(narrativeForHealth(health, completionRate, overdue, daysRemaining));

        String summary = s.toString();
        List<String> recommendations = buildRecommendations(
                health, overdue, todo, inProgress, completionRate, daysRemaining, total);
        String source = SOURCE_MOCK;

        // Attempt to upgrade the narrative with the live model; keep rule-based numbers intact.
        Optional<AiNarrative> ai = tryAiSummary(project, tasks, total, completed, inProgress,
                overdue, todo, completionRate, daysRemaining, health);
        if (ai.isPresent()) {
            summary = ai.get().summary;
            if (!ai.get().recommendations.isEmpty()) {
                recommendations = ai.get().recommendations;
            }
            source = SOURCE_AI;
        }

        return ProjectInsightDTO.builder()
                .projectId(project.getId())
                .projectName(project.getName())
                .summary(summary)
                .healthStatus(health)
                .healthHeadline(headline)
                .recommendations(recommendations)
                .totalTasks(total)
                .completedTasks(completed)
                .inProgressTasks(inProgress)
                .overdueTasks(overdue)
                .todoTasks(todo)
                .completionRate(completionRate)
                .daysRemaining(daysRemaining)
                .source(source)
                .generatedAt(LocalDateTime.now())
                .build();
    }

    /** Holder for the model-generated narrative parts of a summary. */
    private static final class AiNarrative {
        final String summary;
        final List<String> recommendations;
        AiNarrative(String summary, List<String> recommendations) {
            this.summary = summary;
            this.recommendations = recommendations;
        }
    }

    private Optional<AiNarrative> tryAiSummary(Project project, List<Task> tasks, long total,
                                              long completed, long inProgress, long overdue, long todo,
                                              double completionRate, Integer daysRemaining, String health) {
        if (!anyAiEnabled()) {
            return Optional.empty();
        }
        try {
            var mapper = objectMapper;
            var payload = mapper.createObjectNode();
            payload.put("projectName", project.getName());
            payload.put("totalTasks", total);
            payload.put("completedTasks", completed);
            payload.put("inProgressTasks", inProgress);
            payload.put("todoTasks", todo);
            payload.put("overdueTasks", overdue);
            payload.put("completionRate", completionRate);
            if (daysRemaining != null) payload.put("daysRemaining", daysRemaining);
            payload.put("computedHealth", health);
            var taskArray = payload.putArray("tasks");
            for (Task t : tasks) {
                var node = taskArray.addObject();
                node.put("name", t.getName());
                node.put("status", t.getStatus() != null ? t.getStatus().name() : "TODO");
                node.put("priority", t.getPriority() != null ? t.getPriority().name() : "MEDIUM");
                node.put("progress", t.getProgress() != null ? t.getProgress() : 0);
                node.put("deadline", t.getDeadline() != null ? t.getDeadline().toString() : null);
            }
            String payloadJson = mapper.writeValueAsString(payload);
            Optional<String> response = langChainClient.complete(withLanguage(SUMMARY_SYSTEM_PROMPT), payloadJson);
            if (response.isEmpty()) return Optional.empty();

            JsonNode json = parseJsonObject(response.get(), mapper);
            if (json == null || !json.hasNonNull("summary")) return Optional.empty();
            String summary = json.get("summary").asText().trim();
            if (summary.isEmpty()) return Optional.empty();

            List<String> recs = new ArrayList<>();
            JsonNode recNode = json.path("recommendations");
            if (recNode.isArray()) {
                for (JsonNode r : recNode) {
                    String text = r.asText().trim();
                    if (!text.isEmpty()) recs.add(text);
                }
            }
            return Optional.of(new AiNarrative(summary, recs));
        } catch (Exception e) {
            return Optional.empty();
        }
    }

    private String narrativeForHealth(String health, double completionRate, long overdue, Integer daysRemaining) {
        switch (health) {
            case "OFF_TRACK":
                return "Assessment: the project is off track. The combination of overdue work and "
                        + "limited progress suggests the current plan is at risk. Re-baselining scope or "
                        + "deadlines, and clearing blockers on overdue tasks, should be the priority.";
            case "AT_RISK":
                return "Assessment: the project is at risk. Progress is being made, but deadline pressure "
                        + "or a few slipping tasks could compromise delivery. Close monitoring and a focused "
                        + "push on the highest-urgency tasks are recommended.";
            default:
                return "Assessment: the project is on track. Progress is consistent with the timeline and "
                        + "there are no critical blockers. Maintain the current cadence and keep an eye on "
                        + "upcoming deadlines.";
        }
    }

    private List<String> buildRecommendations(String health, long overdue, long todo, long inProgress,
                                              double completionRate, Integer daysRemaining, long total) {
        List<String> recs = new ArrayList<>();
        if (overdue > 0) {
            recs.add("Resolve the " + overdue + " overdue task" + (overdue == 1 ? "" : "s")
                    + " first - reassign, re-scope, or extend their deadlines.");
        }
        if (daysRemaining != null && daysRemaining <= 7 && completionRate < 80 && total > 0) {
            recs.add("The deadline is close (" + Math.max(daysRemaining, 0)
                    + " days) while completion is at " + completionRate
                    + "% - consider reducing scope or adding capacity.");
        }
        if (todo > 0 && inProgress == 0) {
            recs.add("No task is in progress yet - kick off the " + todo
                    + " backlog item" + (todo == 1 ? "" : "s") + " to build momentum.");
        }
        if (inProgress > 5) {
            recs.add("Work is spread across " + inProgress + " concurrent tasks - limit work-in-progress "
                    + "to improve focus and throughput.");
        }
        if (total == 0) {
            recs.add("No tasks have been created for this project yet - break the work down into tasks "
                    + "to enable tracking.");
        }
        if (recs.isEmpty()) {
            recs.add("No corrective action needed - keep the current pace and review deadlines weekly.");
        }
        return recs;
    }

    // ── Prioritisation engine ────────────────────────────────────────────────

    private PrioritizationResultDTO buildSuggestions(Project project, List<Task> tasks) {
        List<TaskPrioritySuggestionDTO> suggestions = new ArrayList<>();

        for (Task task : tasks) {
            if (task.getStatus() == Task.TaskStatus.COMPLETED) {
                continue; // only open work needs prioritising
            }
            int score = urgencyScore(task);
            String suggested = scoreToPriority(score);
            String current = task.getPriority() != null ? task.getPriority().name() : "MEDIUM";

            suggestions.add(TaskPrioritySuggestionDTO.builder()
                    .taskId(task.getId())
                    .taskName(task.getName())
                    .assignedToName(displayName(task.getAssignedTo()))
                    .currentPriority(current)
                    .suggestedPriority(suggested)
                    .changeRecommended(!suggested.equals(current))
                    .urgencyScore(score)
                    .reason(reasonFor(task, score))
                    .build());
        }

        suggestions.sort(Comparator.comparingInt(TaskPrioritySuggestionDTO::getUrgencyScore).reversed());

        long changes = suggestions.stream().filter(TaskPrioritySuggestionDTO::isChangeRecommended).count();
        String advice = suggestions.isEmpty()
                ? "No open tasks to prioritise - everything is completed or the project has no tasks."
                : "Reviewed " + suggestions.size() + " open task" + (suggestions.size() == 1 ? "" : "s")
                  + "; " + changes + " would benefit from a priority change. Start at the top of the list.";
        String source = SOURCE_MOCK;

        // Attempt to enrich the advice and per-task reasons with the live model; keep deterministic scores.
        if (!suggestions.isEmpty()) {
            Optional<AiPriorityText> ai = tryAiPriorities(project, suggestions);
            if (ai.isPresent()) {
                if (ai.get().overallAdvice != null && !ai.get().overallAdvice.isBlank()) {
                    advice = ai.get().overallAdvice;
                }
                for (TaskPrioritySuggestionDTO s : suggestions) {
                    String reason = ai.get().reasonsByTaskId.get(s.getTaskId());
                    if (reason != null && !reason.isBlank()) {
                        s.setReason(reason);
                    }
                }
                source = SOURCE_AI;
            }
        }

        return PrioritizationResultDTO.builder()
                .projectId(project.getId())
                .projectName(project.getName())
                .overallAdvice(advice)
                .suggestions(suggestions)
                .source(source)
                .generatedAt(LocalDateTime.now())
                .build();
    }

    /** Holder for the model-generated text of a prioritisation pass. */
    private static final class AiPriorityText {
        final String overallAdvice;
        final Map<Long, String> reasonsByTaskId;
        AiPriorityText(String overallAdvice, Map<Long, String> reasonsByTaskId) {
            this.overallAdvice = overallAdvice;
            this.reasonsByTaskId = reasonsByTaskId;
        }
    }

    private Optional<AiPriorityText> tryAiPriorities(Project project, List<TaskPrioritySuggestionDTO> suggestions) {
        if (!anyAiEnabled()) {
            return Optional.empty();
        }
        try {
            var mapper = objectMapper;
            var payload = mapper.createObjectNode();
            payload.put("projectName", project.getName());
            var taskArray = payload.putArray("tasks");
            for (TaskPrioritySuggestionDTO s : suggestions) {
                var node = taskArray.addObject();
                node.put("taskId", s.getTaskId());
                node.put("taskName", s.getTaskName());
                node.put("currentPriority", s.getCurrentPriority());
                node.put("suggestedPriority", s.getSuggestedPriority());
                node.put("urgencyScore", s.getUrgencyScore());
            }
            String payloadJson = mapper.writeValueAsString(payload);
            Optional<String> response = langChainClient.complete(withLanguage(PRIORITIES_SYSTEM_PROMPT), payloadJson);
            if (response.isEmpty()) return Optional.empty();

            JsonNode json = parseJsonObject(response.get(), mapper);
            if (json == null) return Optional.empty();

            String overallAdvice = json.hasNonNull("overallAdvice") ? json.get("overallAdvice").asText() : null;
            Map<Long, String> reasons = new HashMap<>();
            JsonNode reasonNode = json.path("reasons");
            if (reasonNode.isArray()) {
                for (JsonNode r : reasonNode) {
                    if (r.hasNonNull("taskId") && r.hasNonNull("reason")) {
                        reasons.put(r.get("taskId").asLong(), r.get("reason").asText().trim());
                    }
                }
            }
            if (overallAdvice == null && reasons.isEmpty()) return Optional.empty();
            return Optional.of(new AiPriorityText(overallAdvice, reasons));
        } catch (Exception e) {
            return Optional.empty();
        }
    }

    /**
     * Parse the model's text into a JSON object, tolerating markdown code fences or stray prose
     * by extracting the first {@code { ... }} block.
     */
    private JsonNode parseJsonObject(String text, com.fasterxml.jackson.databind.ObjectMapper mapper) {
        try {
            return mapper.readTree(text);
        } catch (Exception ignored) {
            int start = text.indexOf('{');
            int end = text.lastIndexOf('}');
            if (start >= 0 && end > start) {
                try {
                    return mapper.readTree(text.substring(start, end + 1));
                } catch (Exception ignored2) {
                    return null;
                }
            }
            return null;
        }
    }

    /**
     * Composite 0-100 urgency score combining base priority, deadline proximity,
     * overdue status, progress gap and a small bump for stalled backlog items.
     */
    private int urgencyScore(Task task) {
        int score = 0;

        // Base weight from the manager-set priority (0-40).
        if (task.getPriority() != null) {
            switch (task.getPriority()) {
                case CRITICAL: score += 40; break;
                case HIGH:     score += 30; break;
                case MEDIUM:   score += 18; break;
                case LOW:      score += 8;  break;
            }
        } else {
            score += 18;
        }

        // Deadline proximity / overdue (0-40).
        LocalDate deadline = task.getDeadline();
        if (deadline != null) {
            long days = ChronoUnit.DAYS.between(LocalDate.now(), deadline);
            if (days < 0)        score += 40;          // overdue
            else if (days == 0)  score += 34;          // due today
            else if (days <= 3)  score += 28;
            else if (days <= 7)  score += 18;
            else if (days <= 14) score += 10;
            else                 score += 4;
        }

        // Progress gap (0-15): less done = more urgent.
        int progress = task.getProgress() != null ? task.getProgress() : 0;
        score += Math.round((100 - Math.min(100, Math.max(0, progress))) / 100f * 15);

        // Stalled backlog bump (0-5).
        if (task.getStatus() == Task.TaskStatus.TODO) {
            score += 5;
        }

        return Math.min(100, score);
    }

    private String scoreToPriority(int score) {
        if (score >= 75) return "CRITICAL";
        if (score >= 55) return "HIGH";
        if (score >= 30) return "MEDIUM";
        return "LOW";
    }

    private String reasonFor(Task task, int score) {
        List<String> parts = new ArrayList<>();
        LocalDate deadline = task.getDeadline();
        if (deadline != null) {
            long days = ChronoUnit.DAYS.between(LocalDate.now(), deadline);
            if (days < 0) parts.add("overdue by " + Math.abs(days) + " day" + (Math.abs(days) == 1 ? "" : "s"));
            else if (days == 0) parts.add("due today");
            else if (days <= 3) parts.add("due in " + days + " day" + (days == 1 ? "" : "s"));
            else if (days <= 7) parts.add("due this week");
        }
        int progress = task.getProgress() != null ? task.getProgress() : 0;
        if (progress == 0 && task.getStatus() != Task.TaskStatus.COMPLETED) parts.add("not started");
        else if (progress < 50) parts.add("only " + progress + "% done");
        if (task.getPriority() == Task.TaskPriority.CRITICAL || task.getPriority() == Task.TaskPriority.HIGH) {
            parts.add("flagged " + task.getPriority().name().toLowerCase());
        }
        if (parts.isEmpty()) parts.add("on schedule with no risk signals");
        return "Urgency " + score + "/100 - " + String.join(", ", parts) + ".";
    }

    // ── Risk prediction engine ───────────────────────────────────────────────

    private RiskAssessmentDTO buildRiskAssessment(Project project, List<Task> tasks) {
        LocalDate today = LocalDate.now();
        List<TaskRiskDTO> risks = new ArrayList<>();

        LocalDate latestPredictedFinish = null;
        for (Task task : tasks) {
            if (task.getStatus() == Task.TaskStatus.COMPLETED) {
                continue; // only open work can slip
            }
            TaskRiskDTO risk = computeTaskRisk(task, today);
            risks.add(risk);
            if (risk.getPredictedCompletionDate() != null) {
                LocalDate pf = LocalDate.parse(risk.getPredictedCompletionDate());
                if (latestPredictedFinish == null || pf.isAfter(latestPredictedFinish)) {
                    latestPredictedFinish = pf;
                }
            }
        }

        // Order most-risky first, then by predicted slip.
        risks.sort(Comparator
                .comparingInt((TaskRiskDTO r) -> riskRank(r.getRiskLevel())).reversed()
                .thenComparing(Comparator.comparingInt(TaskRiskDTO::getPredictedSlipDays).reversed()));

        int totalOpen = risks.size();
        int atRiskCount = (int) risks.stream()
                .filter(r -> riskRank(r.getRiskLevel()) >= 2) // MEDIUM and above
                .count();

        // Project-level risk: driven by the worst task and the predicted project slip.
        int worstRank = risks.stream().mapToInt(r -> riskRank(r.getRiskLevel())).max().orElse(1);
        int projectSlipDays = 0;
        String predictedProjectCompletion = latestPredictedFinish != null ? latestPredictedFinish.toString() : null;
        if (latestPredictedFinish != null && project.getEndDate() != null) {
            projectSlipDays = (int) Math.max(0, ChronoUnit.DAYS.between(project.getEndDate(), latestPredictedFinish));
        }
        String projectRiskLevel = projectRiskLevel(worstRank, projectSlipDays, totalOpen);
        String headline = riskHeadline(projectRiskLevel, atRiskCount);

        String summary = buildRiskSummary(project, totalOpen, atRiskCount, projectRiskLevel,
                predictedProjectCompletion, projectSlipDays);
        String source = SOURCE_MOCK;

        Optional<String> aiSummary = tryAiRiskNarrative(project, projectRiskLevel, projectSlipDays,
                predictedProjectCompletion, atRiskCount, totalOpen, risks);
        if (aiSummary.isPresent()) {
            summary = aiSummary.get();
            source = SOURCE_AI;
        }

        return RiskAssessmentDTO.builder()
                .projectId(project.getId())
                .projectName(project.getName())
                .projectRiskLevel(projectRiskLevel)
                .headline(headline)
                .summary(summary)
                .atRiskCount(atRiskCount)
                .totalOpenTasks(totalOpen)
                .predictedProjectCompletion(predictedProjectCompletion)
                .projectDeadline(project.getEndDate() != null ? project.getEndDate().toString() : null)
                .projectSlipDays(projectSlipDays)
                .risks(risks)
                .source(source)
                .generatedAt(LocalDateTime.now())
                .build();
    }

    /**
     * Predict whether a single open task will miss its deadline. Uses progress velocity
     * (progress since creation) when available, falling back to a required-pace heuristic.
     */
    private TaskRiskDTO computeTaskRisk(Task task, LocalDate today) {
        int progress = task.getProgress() != null ? Math.min(100, Math.max(0, task.getProgress())) : 0;
        LocalDate deadline = task.getDeadline();

        TaskRiskDTO.TaskRiskDTOBuilder b = TaskRiskDTO.builder()
                .taskId(task.getId())
                .taskName(task.getName())
                .assignedToName(displayName(task.getAssignedTo()))
                .deadline(deadline != null ? deadline.toString() : null)
                .progress(progress);

        if (deadline == null) {
            return b.riskLevel("LOW").predictedSlipDays(0).predictedCompletionDate(null)
                    .reason("No deadline set; slip cannot be predicted.").build();
        }

        long daysToDeadline = ChronoUnit.DAYS.between(today, deadline);
        long remaining = 100 - progress;

        if (daysToDeadline < 0) {
            long lateBy = Math.abs(daysToDeadline);
            return b.riskLevel("CRITICAL").predictedSlipDays((int) lateBy).predictedCompletionDate(null)
                    .reason("Already overdue by " + lateBy + " day" + (lateBy == 1 ? "" : "s")
                            + " at " + progress + "% complete.").build();
        }

        // Progress velocity (% per day) since the task was created, when we have a creation date.
        Double velocity = null;
        if (task.getCreatedAt() != null) {
            long elapsed = Math.max(1, ChronoUnit.DAYS.between(task.getCreatedAt().toLocalDate(), today));
            velocity = (double) progress / elapsed;
        }

        if (velocity != null && velocity > 0) {
            long daysToFinish = (long) Math.ceil(remaining / velocity);
            LocalDate predictedFinish = today.plusDays(daysToFinish);
            long slip = ChronoUnit.DAYS.between(deadline, predictedFinish); // >0 means late
            String level = slip > 14 ? "CRITICAL" : slip >= 4 ? "HIGH" : slip >= 1 ? "MEDIUM" : "LOW";
            String reason = slip > 0
                    ? "At the current pace (" + round1(velocity) + "%/day) it will finish around "
                      + predictedFinish + ", about " + slip + " day" + (slip == 1 ? "" : "s") + " late."
                    : "On track at " + round1(velocity) + "%/day; projected to finish by the deadline.";
            return b.riskLevel(level).predictedSlipDays((int) Math.max(0, slip))
                    .predictedCompletionDate(predictedFinish.toString()).reason(reason).build();
        }

        // No measurable progress trend — fall back to the pace the task would now require.
        if (remaining == 0) {
            return b.riskLevel("LOW").predictedSlipDays(0).predictedCompletionDate(today.toString())
                    .reason("Work is complete pending status update.").build();
        }
        double requiredPace = (double) remaining / Math.max(1, daysToDeadline);
        String level = requiredPace > 25 ? "CRITICAL" : requiredPace > 12 ? "HIGH"
                : requiredPace > 6 ? "MEDIUM" : "LOW";
        String reason = "No measurable progress yet; needs about " + round1(requiredPace)
                + "%/day over the next " + daysToDeadline + " day" + (daysToDeadline == 1 ? "" : "s")
                + " to hit the deadline (currently " + progress + "%).";
        return b.riskLevel(level).predictedSlipDays(0).predictedCompletionDate(null).reason(reason).build();
    }

    private String buildRiskSummary(Project project, int totalOpen, int atRiskCount, String level,
                                   String predictedCompletion, int projectSlipDays) {
        if (totalOpen == 0) {
            return "No open tasks to assess - the project has no work at risk of slipping.";
        }
        StringBuilder s = new StringBuilder();
        s.append(atRiskCount).append(" of ").append(totalOpen).append(" open task")
         .append(totalOpen == 1 ? "" : "s").append(" are at risk of missing their deadline. ");
        if (predictedCompletion != null && project.getEndDate() != null) {
            if (projectSlipDays > 0) {
                s.append("At the current pace the project is projected to finish around ")
                 .append(predictedCompletion).append(", about ").append(projectSlipDays)
                 .append(" day").append(projectSlipDays == 1 ? "" : "s").append(" past the planned end date. ");
            } else {
                s.append("At the current pace the project is projected to finish by its planned end date. ");
            }
        }
        switch (level) {
            case "CRITICAL": s.append("Overall delivery risk is critical - intervene now on the most overdue work."); break;
            case "HIGH": s.append("Overall delivery risk is high - act on the at-risk tasks this week."); break;
            case "MEDIUM": s.append("Overall delivery risk is moderate - monitor the flagged tasks closely."); break;
            default: s.append("Overall delivery risk is low.");
        }
        return s.toString();
    }

    private Optional<String> tryAiRiskNarrative(Project project, String projectRiskLevel, int projectSlipDays,
                                               String predictedCompletion, int atRiskCount, int totalOpen,
                                               List<TaskRiskDTO> risks) {
        if (!anyAiEnabled() || totalOpen == 0) {
            return Optional.empty();
        }
        try {
            var mapper = objectMapper;
            var payload = mapper.createObjectNode();
            payload.put("projectName", project.getName());
            payload.put("projectRiskLevel", projectRiskLevel);
            payload.put("projectSlipDays", projectSlipDays);
            payload.put("predictedProjectCompletion", predictedCompletion);
            payload.put("projectDeadline", project.getEndDate() != null ? project.getEndDate().toString() : null);
            payload.put("atRiskCount", atRiskCount);
            payload.put("totalOpenTasks", totalOpen);
            var arr = payload.putArray("tasks");
            for (TaskRiskDTO r : risks) {
                var node = arr.addObject();
                node.put("taskName", r.getTaskName());
                node.put("riskLevel", r.getRiskLevel());
                node.put("predictedSlipDays", r.getPredictedSlipDays());
                node.put("progress", r.getProgress());
                node.put("deadline", r.getDeadline());
            }
            String payloadJson = mapper.writeValueAsString(payload);
            Optional<String> response = langChainClient.complete(withLanguage(RISK_SYSTEM_PROMPT), payloadJson);
            if (response.isEmpty()) return Optional.empty();
            JsonNode json = parseJsonObject(response.get(), mapper);
            if (json == null || !json.hasNonNull("summary")) return Optional.empty();
            String summary = json.get("summary").asText().trim();
            return summary.isEmpty() ? Optional.empty() : Optional.of(summary);
        } catch (Exception e) {
            return Optional.empty();
        }
    }

    private int riskRank(String level) {
        switch (level) {
            case "CRITICAL": return 4;
            case "HIGH": return 3;
            case "MEDIUM": return 2;
            default: return 1; // LOW
        }
    }

    private String projectRiskLevel(int worstTaskRank, int projectSlipDays, int totalOpen) {
        if (totalOpen == 0) return "LOW";
        int slipRank = projectSlipDays > 14 ? 4 : projectSlipDays >= 4 ? 3 : projectSlipDays >= 1 ? 2 : 1;
        int rank = Math.max(worstTaskRank, slipRank);
        switch (rank) {
            case 4: return "CRITICAL";
            case 3: return "HIGH";
            case 2: return "MEDIUM";
            default: return "LOW";
        }
    }

    private String riskHeadline(String level, int atRiskCount) {
        switch (level) {
            case "CRITICAL": return "Critical delivery risk - intervention needed";
            case "HIGH": return "High delivery risk - " + atRiskCount + " task" + (atRiskCount == 1 ? "" : "s") + " at risk";
            case "MEDIUM": return "Moderate delivery risk - monitor closely";
            default: return "On track - low delivery risk";
        }
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private String computeHealth(double completionRate, long overdue, long total, Project project) {
        if (total == 0) return "AT_RISK";
        double overdueRatio = (double) overdue / total;
        Integer daysRemaining = daysRemaining(project);
        boolean deadlinePressure = daysRemaining != null && daysRemaining <= 7 && completionRate < 70;

        if (overdueRatio >= 0.30 || (daysRemaining != null && daysRemaining < 0 && completionRate < 90)) {
            return "OFF_TRACK";
        }
        if (overdueRatio > 0 || deadlinePressure || completionRate < 40) {
            return "AT_RISK";
        }
        return "ON_TRACK";
    }

    private String healthHeadline(String health, long overdue) {
        switch (health) {
            case "OFF_TRACK": return "Off track - intervention needed";
            case "AT_RISK":   return overdue > 0 ? "At risk - overdue tasks detected" : "At risk - monitor closely";
            default:          return "On track";
        }
    }

    private Integer daysRemaining(Project project) {
        if (project.getEndDate() == null) return null;
        return (int) ChronoUnit.DAYS.between(LocalDate.now(), project.getEndDate());
    }

    private String displayName(com.example.gpiApp.entity.allUsers user) {
        if (user == null) return "Unassigned";
        String first = user.getFirstName() != null ? user.getFirstName() : "";
        String last = user.getLastName() != null ? user.getLastName() : "";
        String full = (first + " " + last).trim();
        if (!full.isEmpty()) return full;
        return user.getUsername() != null ? user.getUsername() : "Unassigned";
    }

    private long count(List<Task> tasks, Task.TaskStatus status) {
        return tasks.stream().filter(t -> t.getStatus() == status).count();
    }

    private long countOverdue(List<Task> tasks) {
        LocalDate today = LocalDate.now();
        return tasks.stream()
                .filter(t -> t.getStatus() != Task.TaskStatus.COMPLETED)
                .filter(t -> t.getDeadline() != null && t.getDeadline().isBefore(today))
                .count();
    }

    private double round1(double v) {
        return Math.round(v * 10.0) / 10.0;
    }
}
